In [1]:
# 책에 없는 내
# 100MB이상은 wget사용 안됨

In [2]:
!wget –no-check-certificate 'https://docs.google.com/uc?export=download&id=1zqBTPftlJs5h87atXKo6d1PxFTbRvNzj' -O test.zip

--2024-04-19 01:43:51--  http://xn--no-check-certificate-2t2l/
Resolving xn--no-check-certificate-2t2l (xn--no-check-certificate-2t2l)... failed: Name or service not known.
wget: unable to resolve host address ‘xn--no-check-certificate-2t2l’
--2024-04-19 01:43:51--  https://docs.google.com/uc?export=download&id=1zqBTPftlJs5h87atXKo6d1PxFTbRvNzj
Resolving docs.google.com (docs.google.com)... 142.250.125.101, 142.250.125.139, 142.250.125.138, ...
Connecting to docs.google.com (docs.google.com)|142.250.125.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1zqBTPftlJs5h87atXKo6d1PxFTbRvNzj&export=download [following]
--2024-04-19 01:43:51--  https://drive.usercontent.google.com/download?id=1zqBTPftlJs5h87atXKo6d1PxFTbRvNzj&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 209.85.145.132, 2607:f8b0:4001:c1e::84
Connecting to drive.usercontent.google.com (drive.usercon

In [3]:
!unzip test.zip

Archive:  test.zip
  inflating: test_images/01.jpg      
  inflating: test_images/02.jpg      
  inflating: test_images/03.jpg      
  inflating: test_images/04.jpg      
  inflating: test_images/05.jpg      
  inflating: test_images/06.jpg      
  inflating: test_images/07.jpg      
  inflating: test_images/08.jpg      
  inflating: test_images/09.jpg      
  inflating: test_images/10.jpg      
  inflating: test_images/11.jpg      
  inflating: test_images/12.jpg      
  inflating: test_images/label.txt   


In [4]:
import numpy as np
import tensorflow as tf
from PIL import Image
from glob import glob
import os

In [5]:
# 자신의 구굴 드라이브 내 모델 위치
# 자신의 구글 드라이브내의 모델 위치
cnn_model = tf.keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/best_model.keras')
cnn_model

In [6]:
target_name = [
'airplane'                    ,
'automobile'                  ,
'bird'                    ,
'cat'                   ,
'deer'                  ,
'dog'                   ,
'frog'                  ,
'horse'                 ,
'ship'                  ,
'truck',
]

In [7]:
os.listdir('/content/test_images')

['label.txt',
 '02.jpg',
 '11.jpg',
 '03.jpg',
 '04.jpg',
 '09.jpg',
 '05.jpg',
 '12.jpg',
 '07.jpg',
 '08.jpg',
 '06.jpg',
 '01.jpg',
 '10.jpg']

In [8]:
files_list = glob('/content/test_images/*.jpg')
file_names = [path.split('/')[-1] for path in files_list]

In [9]:
# 이미지를 읽어서 - 데이터 ... 사이즈는 학습에 입력으로 들어가 사이즈와 맞춰야 한다.
# CFIR-10 (32,32)
img = Image.open(files_list[0])
np.array(img.resize( (32,32) )) / 255.0

array([[[0.6745098 , 0.63921569, 0.47058824],
        [0.56862745, 0.52941176, 0.39215686],
        [0.3372549 , 0.31372549, 0.14901961],
        ...,
        [0.29019608, 0.27843137, 0.12941176],
        [0.25098039, 0.24313725, 0.10196078],
        [0.23137255, 0.23529412, 0.09411765]],

       [[0.65882353, 0.62352941, 0.45882353],
        [0.54117647, 0.50980392, 0.36470588],
        [0.31764706, 0.30980392, 0.1254902 ],
        ...,
        [0.29411765, 0.28627451, 0.1254902 ],
        [0.24313725, 0.24313725, 0.09411765],
        [0.22352941, 0.23137255, 0.08235294]],

       [[0.60392157, 0.58039216, 0.41960784],
        [0.46666667, 0.45490196, 0.29019608],
        [0.27843137, 0.29411765, 0.0745098 ],
        ...,
        [0.29411765, 0.29019608, 0.12156863],
        [0.24313725, 0.25098039, 0.08627451],
        [0.22745098, 0.23921569, 0.07058824]],

       ...,

       [[0.32156863, 0.34509804, 0.12941176],
        [0.3372549 , 0.34117647, 0.14117647],
        [0.34509804, 0

In [10]:
X_train = []
for filename in files_list :
  img = Image.open(filename)
  X_train.append( np.array(img.resize((32,32)) ) / 25.0)

In [11]:
X_train = np.array(X_train)
X_train.shape   #(12,32,32,3)

(12, 32, 32, 3)

In [12]:
# 예측
preds = cnn_model.predict(X_train)


1/1 [==============================] - 2s 2s/step


In [13]:
preds[0]

array([7.1320022e-13, 8.1444891e-28, 2.3798515e-05, 6.1566618e-07,
       1.1798212e-25, 9.8999196e-01, 1.4512433e-33, 9.9835340e-03,
       2.0749163e-29, 1.9033008e-23], dtype=float32)

In [18]:
# preds의 가장 큰 값을 가진 인덱스를 알아야함
preds[0], np.argmax(preds[0]), target_name[np.argmax(preds[0])]

(array([7.1320022e-13, 8.1444891e-28, 2.3798515e-05, 6.1566618e-07,
        1.1798212e-25, 9.8999196e-01, 1.4512433e-33, 9.9835340e-03,
        2.0749163e-29, 1.9033008e-23], dtype=float32),
 5,
 'dog')

In [19]:
[target_name[np.argmax(p)] for p in preds]

['dog',
 'truck',
 'automobile',
 'dog',
 'ship',
 'truck',
 'horse',
 'frog',
 'deer',
 'dog',
 'airplane',
 'ship']

In [21]:
# 예측한 이름으로 directory 만들고 (이미 있으면 안만든다)
# 해당 이미지를 copy 한다.
os.mkdir("test")

In [23]:
os.path.isdir("test")

True

In [24]:
# 분류별로 폴더 만들기
# 분류한 이미지를 해당 폴더로 복사하기

In [29]:
pwd

'/content'

In [34]:
if not os.path.isdir('predict'):
  os.mkdir('predict')
  # 해당 위치로 이동
os.chdir('./predict')

In [35]:
# 분류별로 폴더 만들기
for name in target_name:
  if not os.path.isdir(name):
    os.mkdir(name)

In [39]:
# 예측한 이름에 해당하는 폴더로 해당 이미지 복사(이동)
# 예측한 이름
import shutil     # 복사 라이브러리
os.chdir('/content/predict')

predict_names = [target_name[np.argmax(p)]for p in preds]
for name,file in zip(predict_names,files_list) :
  target_path = '/content/predict/'+name+'/'
  file_name = file.split('/')[-1]
  os.chdir(name)    # 해당 폴더로 이동
  shutil.copyfile(file,target_path+file_name)       # 오리지널 파일을 해당 폴더의 오리지널 파일명으로 복사
  os.chdir('../')     # 다시 한단계 위로 이